// auth
export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE';
export const AUTH_USER= 'AUTH_USER';
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESSS = 'AUTH_SUCCESS';
export const AUTH_FAILDED = 'AUTH_FAILDED';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIAL_LOGOUT = 'AUTH_INITIAL_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

//burger
export const ADD_INGREDIENT ='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const SET_INGREDIENTS ='SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED ='FETCH_INGREDIENTS_FAILED';
export const INIT_INGREDIENTS ='INIT_INGREDIENTS';

//order purchase buger
export const PURCHASE_BUGER = 'PURCHASE_BUGER';
export const PURCHASE_BUGER_START = 'PURCHASE_BUGER_START';
export const PURCHASE_BUGER_SUCCESS = 'PURCHASE_BUGER_SUCCESS';
export const PURCHASE_BUGER_FAILED= 'PURCHASE_BUGER_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

//order buger
export const FETCH_ORDER='FETCH_ORDER';
export const FETCH_ORDER_INIT ='FETCH_ORDER_INIT';
export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED ='FETCH_ORDER_FAILED';
export const FETCH_ORDER_START ='FETCH_ORDER_START';

//profile
export const PROFILE_GET_DATA = 'PROFILE_GET_DATA';
export const PROFILE_GET_DATA_START = 'PROFILE_GET_DATA_START';
export const PROFILE_GET_DATA_SUCCESS = 'PROFILE_GET_DATA_SUCCESS';
export const PROFILE_GET_DATA_FAILED = 'PROFILE_GET_DATA_FAILED';
export const PROFILE_UPDATE_DATA = 'PROFILE_UPDATE_DATA';
export const PROFILE_UPDATE_DATA_STATUS = 'PROFILE_UPDATE_DATA_STATUS';


